### ISSUE TITLE
Problems with registration

### ISSUE THREAD

**Issue by drmenzelit** [cmextension/cmavatar#1]
Hi,
we are having problems with the registration on our website using CM Avatar: Unable to upload file. Though the field for avatar upload is optional.
Can you please give us advice?
http://www.j-over.de/de/neuen-account-anlegen.html

Thank you
Viviana

**Comment by tranduyhung** [comment]
Hi Viviana,

I just released 1.1.0 to fix this problem and add an option to control avatar's height. Please download and try it. If you find any problem please let me know.

Regards,
Hung

**Comment by drmenzelit** [comment]
Great, it works! Thank you
