### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by GitHubincus** [cmextension/cmavatar#7]
![avatar error](https://cloud.githubusercontent.com/assets/19427234/15529840/78726b84-227a-11e6-9759-0aed9dcc3d6f.jpg)
I am using Joomla 3.5.1-1, , i installed your most recent extension, at first it seems to work as it show the module and i can select a picture to upload, but when the upload its completed it only show a little tiny white broken square, no pictures at all.
I tried to delete the cache and open a new window, but it still doesn't work.
I am not sure if the PHP cache being disabled has got anything to do with this problem, can you please advise what it would be better to do?
Thanks

**Comment by tranduyhung** [comment]
You can try to install the version in 1.2.0 branch to see if it fixes your problem.

**Comment by GitHubincus** [comment]
Sorry i am a complete newbie and i am not sure of what do you mean.  
Do i have to install a previous version of Avatar or reinstall the current version into a different place?
Thanks

**Comment by GitHubincus** [comment]
![cache conf](https://cloud.githubusercontent.com/assets/19427234/15530078/58d6815a-227c-11e6-9269-bbdc587aed5d.jpg)

![system info](https://cloud.githubusercontent.com/assets/19427234/15530190/20879400-227d-11e6-9912-d0385e562715.jpg)

**Comment by tranduyhung** [comment]
You can go to https://github.com/cmextension/cmavatar/tree/1.2.0, click the green button Clone Or Download, then click Download button. Install the downloaded package as regular Joomla extension.

**Comment by GitHubincus** [comment]
Okay that's great! 
I will give it a try right now without disinstalling or modify anything else, thanks.

**Comment by GitHubincus** [comment]
Unfortunately i had no luck....
I downloaded the new zip (v.1.2), installed it, but i couldn't see the new plugin, maybe it just merged with the old one that was still switched on....maybe i need to first disable and uninstall the previous version?
I will try this now has the problem its still there

**Comment by GitHubincus** [comment]
Nothing works :( 
I disabled and then uninstalled the version 1.1, cleared the expired cache, close the window and opened a new one, installed the version 1.2, ticked the box inside it to make sure the picture is displayed on profile, enabled it, still the same.
I then went to Extensions>>Manage>>Manage because there it show me the currently installed versions numbers, and weirdly it shows the new version its still "1.1.1, 17 October 2015"....why???

**Comment by tranduyhung** [comment]
What the URL of your profile form looks like?
Ignore the version number, it doesn't matter. 1.2.0 is not released and the version number is not increased yet.

**Comment by GitHubincus** [comment]
The URL is just the default one assigned by the system : http://127.0.0.1:8080/joomla/index.php/your-profile

**Comment by GitHubincus** [comment]
I enabled the system's cache, just to see if it would made any differences, still no joy :( 
Does anyone have any possible suggestions? I am not sure of what else i could try, i am on CentOS 6.7, maybe it's Selinux blocking it? Or maybe i should move the pictures i am using into a different folder, or check the folder being used by CMavatar has the right permissions???

**Comment by tranduyhung** [comment]
I also have CentOS here and I don't have this problem at all. If your site is online, I can take a look at it. You can reach me via my personal email nguyentieuhau@gmail.com whenever you want to give me access to your site.

**Comment by GitHubincus** [comment]
Sure, i will send you an email now with the details, thank you so much
